SELECT ROUTE,
CONCAT(ROUND(sum(D_BETWEEN_DIST),1),"km") TOTAL_DISTANCE ,
CONCAT(ROUND(avg(D_BETWEEN_DIST),2),"km") AVERAGE_DISTANCE
FROM SUBWAY_DISTANCE
GROUP BY ROUTE
ORDER BY sum(D_BETWEEN_DIST) desc;