-- 코드를 작성해주세요

SELECT  e.EMP_NO, e.EMP_NAME,
CASE 
    WHEN AVG(SCORE)>=96 then 'S'
    WHEN AVG(SCORE)>=90 then 'A'
    WHEN AVG(SCORE)>=80 then 'B'
    ELSE 'C'
END as GRADE,
CASE 
    WHEN AVG(SCORE)>=96 then SAL*0.2
    WHEN AVG(SCORE)>=90 then SAL*0.15
    WHEN AVG(SCORE)>=80 then SAL*0.1
    ELSE 0
END as BONUS
FROM HR_EMPLOYEES e
JOIN HR_DEPARTMENT d
USING (DEPT_ID)
JOIN HR_GRADE g
USING (EMP_NO)
GROUP BY EMP_NO
ORDER BY e.EMP_NO