-- 코드를 입력하세요
SELECT mp.MEMBER_NAME, rr.REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,'%Y-%m-%d') REVIEW_DATE
FROM REST_REVIEW rr 
JOIN MEMBER_PROFILE mp
ON mp.MEMBER_ID = rr.MEMBER_ID
WHERE rr.MEMBER_ID = (SELECT MEMBER_ID
                  FROM REST_REVIEW
                  GROUP BY MEMBER_ID
                  ORDER BY COUNT(*) DESC
                  LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT;