-- 코드를 입력하세요
SELECT DISTINCT cr.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR cr
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY ch
ON cr.CAR_ID = ch.CAR_ID
WHERE MONTH(ch.START_DATE) = '10'
AND CAR_TYPE = '세단'
ORDER BY cr.CAR_ID DESC;